# Generated by Django 5.1.1 on 2024-09-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('passport_front_ids', models.JSONField(blank=True, default=list)),
                ('passport_back_ids', models.JSONField(blank=True, default=list)),
                ('front_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('back_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('prava_ids', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.ImageField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.bot_user')),
            ],
        ),
    ]
