# Generated by Django 5.1.1 on 2024-09-23 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot_user',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('waiting', 'kutilmoqda'), ('canceled', 'Bekor qilingan'), ('finished', 'Tugatilgan')], default='waiting', max_length=10),
            preserve_default=False,
        ),
    ]
