# Generated by Django 5.1.1 on 2024-09-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bot_user_created_at_bot_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_user',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('waiting', 'Kutilmoqda'), ('canceled', 'Bekor qilingan'), ('finished', 'Tugatilgan')], default='waiting', max_length=10),
        ),
    ]
