# Generated by Django 5.1.1 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bot_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
