# Generated by Django 5.1.1 on 2024-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bot_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
