# Generated by Django 5.1.1 on 2024-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bot_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_user',
            name='username',
            field=models.CharField(blank=True, default='not Found', max_length=150),
            preserve_default=False,
        ),
    ]
