# Generated by Django 5.1.1 on 2024-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bot_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_user',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
