# Generated by Django 5.1.1 on 2024-09-26 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_bot_user_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_user',
            name='payment',
        ),
    ]
