# Generated by Django 5.1.1 on 2024-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_bot_user_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
