# Generated by Django 5.1.1 on 2024-09-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bot_user_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot_user',
            name='back_tex_passport_ids',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='front_tex_passport_ids',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='passport_back_ids',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='passport_front_ids',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='prava_ids',
        ),
        migrations.RemoveField(
            model_name='bot_user',
            name='status',
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Qabul qilingan'), ('waiting', 'Kutilmoqda'), ('canceled', 'Bekor qilingan'), ('finished', 'Tugatilgan')], default='waiting', max_length=10)),
                ('passport_front_ids', models.JSONField(blank=True, default=list)),
                ('passport_back_ids', models.JSONField(blank=True, default=list)),
                ('front_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('back_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('prava_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='app.bot_user')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
