# Generated by Django 5.1.1 on 2024-09-26 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_bot_user_back_tex_passport_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='user',
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('accepted', 'Qabul qilingan'), ('waiting', 'Kutilmoqda'), ('canceled', 'Bekor qilingan'), ('finished', 'Tugatilgan')], default='waiting', max_length=10)),
                ('passport_front_ids', models.JSONField(blank=True, default=list)),
                ('passport_back_ids', models.JSONField(blank=True, default=list)),
                ('front_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('back_tex_passport_ids', models.JSONField(blank=True, default=list)),
                ('prava_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='app.tguser')),
            ],
        ),
        migrations.DeleteModel(
            name='Bot_User',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
