# Generated by Django 5.1.1 on 2024-09-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tguser_remove_insurance_user_botuser_delete_bot_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='user',
            new_name='tg_user',
        ),
    ]
